### ISSUE TITLE
Add gherkin parsing

### ISSUE THREAD

**Issue by alistair-broomhead** [london-python-project-nights/romaine#2]

**Comment by geokala** [comment]
```
Take in feature path; or open file handle, return:
Feature object:
  Description (optional)
  List of scenarios (dicts):
     Description (opt)
     List of step objects (step string __repr__, plus type metadata)
```

**Comment by alistair-broomhead** [comment]
Rather than a path I was thinking that this should take either a file-like-object or the string representation of gherkin text - that way you can test by passing either a raw string, or a StringIO object. I think that adding file path handling to the gherkin parser probably violates Do One Thing and would require more testing.

**Comment by geokala** [comment]
Fair point- perhaps then it should only accept strings, rather than strings and file like objects? Unless file like objects won't add much pain to it- but I think the interfaces differ a fair bit (off the top of my head)?

**Comment by geokala** [comment]
Worth noting the (nearly) BNF for gherkin: https://github.com/cucumber/gherkin/wiki/BNF

Also, Gherkin reference: https://cucumber.io/docs/reference

**Comment by alistair-broomhead** [comment]
My thoughts were that in the case of a string you just wrap it in a
StringIO object

**Comment by geokala** [comment]
Exploring a line based approach at the moment as I think this'll be easier code to follow than the corresponding regex approach (even though regexes are pretty).

https://github.com/geokala/romaine/tree/parser

If this turns out to substantially increase the complexity later then I'll torch it and move to a regex based approach.

**Comment by geokala** [comment]
PR is up: https://github.com/london-python-project-nights/romaine/pull/29

**Comment by alistair-broomhead** [comment]
Completed by #29
