### ISSUE TITLE
logging api

### ISSUE THREAD

**Issue by alistair-broomhead** [london-python-project-nights/romaine#6]

**Comment by alistair-broomhead** [comment]
What do we want here? My guess is that we want a logger on the core, and the core should have methods to print out:
1. Error for an unimplemented step
2. Info for a running step
3. Info for step success
4. Error for step failure
5. Warning for step skipped
6. Run statistics
   - Total number of Features, Scenarios, Steps
   - Number of passed Features, Scenarios, Steps
   - Number of failed Features, Scenarios, Steps
   - Number of skipped Features, Scenarios, Steps
   - Duration of each Feature, Scenario, Step if over some threshold?

**Comment by geokala** [comment]
Those look good, plus some more:
1. From past use of tools that do the sort of discovery we're dealing with here, it would be good to do some debug level output for the feature/step finding:
   DEBUG: Searching for features in <x>, found <y>, <z> are acceptable as features.
   DEBUG: Obtained steps <x> from <y>.
   DEBUG: Asked to run step with string <x> by feature <y>, selected step <z>
2. Warn for empty feature files
3. Warn for step which simply passes(?)- that's effectively an unimplemented step, so should probably cause an alert.

Regarding the statistics... I wonder if we should put them in at a later stage as they introduce a lot more complexity, so probably warrant their own issue.
e.g. the warning if over threshold is good, but we would need to determine how that threshold is set, etc.

**Comment by alistair-broomhead** [comment]
If the threshold of set on the Core object we can leave the runner features for doing so until later?

**Comment by geokala** [comment]
Hmm... I would lean towards not including the thresholds at this stage. We can always introduce them later, with a default of None so that the API behaviour remains the same.

There's a few too many questions/approaches we would need to consider for the threshold part I think, so perhaps we just provide the duration logging output function in this and leave the added complexity until later?

**Comment by alistair-broomhead** [comment]
Sounds fair, fancy adding it to the backlog?

**Comment by geokala** [comment]
Hmm... as I'm writing it it's actually feeling more like something that should be part of the step code itself.

e.g.
Given that I want to do a thing
When I try to do it it under 10 seconds
Then it completes as expected

I'm not 100% sure about how we should approach this- shall we brainstorm it at the next dojo (time permitting) or project night (time permitted)?

**Comment by alistair-broomhead** [comment]
Sure, my thoughts were that it just gives timings to long running tests (more then a second) so you can see what's taking time. I don't mind moving this into a separate ticket though

**Comment by geokala** [comment]
Okay, based on that it's reasonable- I thought you intended to have it able to automagically stop the test if it went over a certain time.

Perhaps not having a threshold but setting the timing statistics output to debug level would be sensible as a starting point? We can then introduce the ability to set thresholds with higher warning levels later.

**Comment by geokala** [comment]
Merged.
